### ISSUE TITLE
Build docker container [Error]

### ISSUE THREAD

**Issue by igorme** [Juniper/open-nti#15] opened 2016-03-06 08:06 UTC
Hi

Step 13
`Downloading/unpacking git+https://github.com/Juniper/py-junos-eznc.git
  Cloning https://github.com/Juniper/py-junos-eznc.git to /tmp/pip-QYpGsX-build
  Running setup.py (path:/tmp/pip-QYpGsX-build/setup.py) egg_info for package from git+https://github.com/Juniper/py-junos-eznc.git
    error in junos-eznc setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in junos-eznc setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-QYpGsX-build
Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip install influxdb &&         pip install xmltodict &&         pip install pexpect &&         easy_install pysnmp &&         pip install lxml &&         pip install python-crontab &&         pip install git+https://github.com/Juniper/py-junos-eznc.git' returned a non-zero code: 1

root@template:~/open-nti# ^C
`

**Comment by 3fr61n** [comment] 2016-03-06 10:22
Hi

Could you please give your test enviroment?  Mac/linux, docker version, etc?

Did you try to build the container many times, all of them with the same error?

Regards

**Comment by igorme** [comment] 2016-03-06 11:23
Hi 

Linux Ubuntu 14.04(LTS) 3.19.0-51-generic

Docker 

`root@template:~/open-nti# docker -v
Docker version 1.10.2, build c3959b1
`
Python 2.7

and yes, every time i try to build the container, same error occurs. i've tried using ubuntu 14.04 and 15.10 for that and there was the same error.

Was doing everything according to this manual https://github.com/Juniper/open-nti/blob/master/README.md

**Comment by lorenzomurillo** [comment] 2016-03-06 15:04
Hello team,
I have the same problem when issuing "sudo ./docker.build.sh"
Any clue to continue the docker build would be appreciated.
Thanks in advance.
Lorenzo



I'm installing it on a Ubuntu 14.04 Desktop:
ubuntu@ubuntu-virtual-machine:~/Documents/open-nti$ docker -v
Docker version 1.10.2, build c3959b1
ubuntu@ubuntu-virtual-machine:~/Documents/open-nti$ uname -a
Linux ubuntu-virtual-machine 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux



ubuntu@ubuntu-virtual-machine:~/Documents/open-nti$ sudo ./docker.build.sh
< You can find full log below >
Cleaning up...
Downloading/unpacking git+https://github.com/Juniper/py-junos-eznc.git
  Cloning https://github.com/Juniper/py-junos-eznc.git to /tmp/pip-3mDfN3-build
  Running setup.py (path:/tmp/pip-3mDfN3-build/setup.py) egg_info for package from git+https://github.com/Juniper/py-junos-eznc.git
    error in junos-eznc setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in junos-eznc setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-3mDfN3-build
Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip install influxdb &&         pip install xmltodict &&         pip install pexpect &&         easy_install pysnmp &&         pip install lxml &&         pip install python-crontab &&         pip install git+https://github.com/Juniper/py-junos-eznc.git' returned a non-zero code: 1
ubuntu@ubuntu-virtual-machine:~/Documents/open-nti$ 





I think the problem is installing py-junos-eznc directly from github.
If you do it, you get the same error report:
ubuntu@ubuntu-virtual-machine:~/Documents/open-nti$ sudo pip install git+https://github.com/Juniper/py-junos-eznc.git
[sudo] password for ubuntu: 
Downloading/unpacking git+https://github.com/Juniper/py-junos-eznc.git
  Cloning https://github.com/Juniper/py-junos-eznc.git to /tmp/pip-odEw85-build
  Running setup.py (path:/tmp/pip-odEw85-build/setup.py) egg_info for package from git+https://github.com/Juniper/py-junos-eznc.git
    error in junos-eznc setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in junos-eznc setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-odEw85-build
Storing debug log for failure in /home/ubuntu/.pip/pip.log
ubuntu@ubuntu-virtual-machine:~/Documents/open-nti$ 







ubuntu@ubuntu-virtual-machine:~/Documents/open-nti$ sudo ./docker.build.sh
Sending build context to Docker daemon 12.87 MB
Step 1 : FROM phusion/baseimage:0.9.18
 ---> 772dd063a060
Step 2 : MAINTAINER Damien Garros <dgarros@gmail.com>
 ---> Using cache
 ---> 44e0381b864e
Step 3 : RUN apt-get -y update &&         apt-get -y upgrade
 ---> Using cache
 ---> 4836f15c4592
Step 4 : RUN apt-get -y --force-yes install         git adduser libfontconfig wget make curl
 ---> Using cache
 ---> c06fbfc3c91c
Step 5 : RUN rm -f /etc/service/sshd/down
 ---> Using cache
 ---> 1b41824c025d
Step 6 : RUN /usr/sbin/enable_insecure_key
 ---> Using cache
 ---> 8053d92e8b05
Step 7 : ENV GRAFANA_VERSION 2.6.0
 ---> Using cache
 ---> 25bd99fc8b2e
Step 8 : ENV INFLUXDB_VERSION 0.9.6.1
 ---> Using cache
 ---> d707ecf7f250
Step 9 : ENV TELEGRAF_VERSION 0.10.1-1
 ---> Using cache
 ---> 5279a5484eda
Step 10 : ENV FLUENTD_VERSION 0.12.20
 ---> Using cache
 ---> d39ab88c67f5
Step 11 : ENV FLUENTD_JUNIPER_VERSION 0.2.6-beta
 ---> Using cache
 ---> 47768e51cacb
Step 12 : RUN apt-get -y update &&         apt-get -y install             build-essential             python-simplejson             python-support             python-dev             python-yaml             python-pip             python-dev             libxml2-dev             libxslt-dev             tcpdump             tree             nginx-light             ruby             ruby-dev             snmp             zlib1g-dev
 ---> Using cache
 ---> a11b6378b67c
Step 13 : RUN pip install influxdb &&         pip install xmltodict &&         pip install pexpect &&         easy_install pysnmp &&         pip install lxml &&         pip install python-crontab &&         pip install git+https://github.com/Juniper/py-junos-eznc.git
 ---> Running in 64ecbc40d1c9
Downloading/unpacking influxdb
Downloading/unpacking six>=1.9.0 (from influxdb)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking python-dateutil>=2.0.0 (from influxdb)
Downloading/unpacking pytz (from influxdb)
Requirement already satisfied (use --upgrade to upgrade): requests>=1.0.3 in /usr/lib/python2.7/dist-packages (from influxdb)
Installing collected packages: influxdb, six, python-dateutil, pytz
  Found existing installation: six 1.5.2
    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed influxdb six python-dateutil pytz
Cleaning up...
Downloading/unpacking xmltodict
  Downloading xmltodict-0.10.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/xmltodict/setup.py) egg_info for package xmltodict
    
Installing collected packages: xmltodict
  Running setup.py install for xmltodict
    
Successfully installed xmltodict
Cleaning up...
Downloading/unpacking pexpect
  Running setup.py (path:/tmp/pip_build_root/pexpect/setup.py) egg_info for package pexpect
    
Downloading/unpacking ptyprocess>=0.5 (from pexpect)
  Downloading ptyprocess-0.5.1-py2.py3-none-any.whl
Installing collected packages: pexpect, ptyprocess
  Running setup.py install for pexpect
      File "/usr/local/lib/python2.7/dist-packages/pexpect/async.py", line 16
        transport, pw = yield from asyncio.get_event_loop()\
                                 ^
    SyntaxError: invalid syntax
    
    
Successfully installed pexpect ptyprocess
Cleaning up...
Searching for pysnmp
Reading https://pypi.python.org/simple/pysnmp/
Best match: pysnmp 4.3.2
Downloading https://pypi.python.org/packages/2.7/p/pysnmp/pysnmp-4.3.2-py2.7.egg#md5=aecf0c01582e2ba7509df3c103df8181
Processing pysnmp-4.3.2-py2.7.egg
Moving pysnmp-4.3.2-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding pysnmp 4.3.2 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pysnmp-4.3.2-py2.7.egg
Processing dependencies for pysnmp
Searching for pycrypto>=2.4.1
Reading https://pypi.python.org/simple/pycrypto/
Best match: pycrypto 2.6.1
Downloading https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.1.tar.gz#md5=55a61a054aa66812daf5161a0d5d7eda
Processing pycrypto-2.6.1.tar.gz
Writing /tmp/easy_install-SxdQj5/pycrypto-2.6.1/setup.cfg
Running pycrypto-2.6.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-SxdQj5/pycrypto-2.6.1/egg-dist-tmp-bN5pAY
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
zip_safe flag not set; analyzing archive contents...
Adding pycrypto 2.6.1 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pycrypto-2.6.1-py2.7-linux-x86_64.egg
Searching for pysmi
Reading https://pypi.python.org/simple/pysmi/
Best match: pysmi 0.0.7
Downloading https://pypi.python.org/packages/2.7/p/pysmi/pysmi-0.0.7-py2.7.egg#md5=f0d5474196991dfce2e52c7474757dce
Processing pysmi-0.0.7-py2.7.egg
Moving pysmi-0.0.7-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding pysmi 0.0.7 to easy-install.pth file
Installing mibdump.py script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/pysmi-0.0.7-py2.7.egg
Searching for pyasn1>=0.1.8
Reading https://pypi.python.org/simple/pyasn1/
Best match: pyasn1 0.1.9
Downloading https://pypi.python.org/packages/2.7/p/pyasn1/pyasn1-0.1.9-py2.7.egg#md5=08eef0e822233609f6cad55b419ae00c
Processing pyasn1-0.1.9-py2.7.egg
Moving pyasn1-0.1.9-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding pyasn1 0.1.9 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pyasn1-0.1.9-py2.7.egg
Searching for ply
Reading https://pypi.python.org/simple/ply/
Best match: ply 3.8
Downloading https://pypi.python.org/packages/source/p/ply/ply-3.8.tar.gz#md5=94726411496c52c87c2b9429b12d5c50
Processing ply-3.8.tar.gz
Writing /tmp/easy_install-bFylI_/ply-3.8/setup.cfg
Running ply-3.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-bFylI_/ply-3.8/egg-dist-tmp-BQ27h9
warning: no previously-included files matching '*.pyc' found anywhere in distribution
zip_safe flag not set; analyzing archive contents...
ply.lex: module references __file__
ply.lex: module MAY be using inspect.getsourcefile
ply.yacc: module references __file__
ply.yacc: module MAY be using inspect.getsourcefile
ply.yacc: module MAY be using inspect.stack
ply.ygen: module references __file__
Adding ply 3.8 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/ply-3.8-py2.7.egg
Finished processing dependencies for pysnmp
Downloading/unpacking lxml
  Running setup.py (path:/tmp/pip_build_root/lxml/setup.py) egg_info for package lxml
    Building lxml version 3.5.0.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    
    warning: no previously-included files found matching '*.py'
Installing collected packages: lxml
  Running setup.py install for lxml
    Building lxml version 3.5.0.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    building 'lxml.etree' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -lxslt -lexslt -lxml2 -lz -lm -o build/lib.linux-x86_64-2.7/lxml/etree.so
    building 'lxml.objectify' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.objectify.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.objectify.o -w
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/lxml/lxml.objectify.o -lxslt -lexslt -lxml2 -lz -lm -o build/lib.linux-x86_64-2.7/lxml/objectify.so
    
Successfully installed lxml
Cleaning up...
Downloading/unpacking python-crontab
  Downloading python-crontab-2.0.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/python-crontab/setup.py) egg_info for package python-crontab
    
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python2.7/dist-packages (from python-crontab)
Installing collected packages: python-crontab
  Running setup.py install for python-crontab
    
Successfully installed python-crontab
Cleaning up...
Downloading/unpacking git+https://github.com/Juniper/py-junos-eznc.git
  Cloning https://github.com/Juniper/py-junos-eznc.git to /tmp/pip-3mDfN3-build
  Running setup.py (path:/tmp/pip-3mDfN3-build/setup.py) egg_info for package from git+https://github.com/Juniper/py-junos-eznc.git
    error in junos-eznc setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in junos-eznc setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-3mDfN3-build
Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip install influxdb &&         pip install xmltodict &&         pip install pexpect &&         easy_install pysnmp &&         pip install lxml &&         pip install python-crontab &&         pip install git+https://github.com/Juniper/py-junos-eznc.git' returned a non-zero code: 1
ubuntu@ubuntu-virtual-machine:~/Documents/open-nti$

**Comment by lorenzomurillo** [comment] 2016-03-06 16:51
Hi team,
unfortunately the same problem when building open-nti on OS-X Yosemite (10.10.5)
Regards,
Lorenzo

Downloading/unpacking git+https://github.com/Juniper/py-junos-eznc.git
  Cloning https://github.com/Juniper/py-junos-eznc.git to /tmp/pip-DVs5ai-build
  Running setup.py (path:/tmp/pip-DVs5ai-build/setup.py) egg_info for package from git+https://github.com/Juniper/py-junos-eznc.git
    error in junos-eznc setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in junos-eznc setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-DVs5ai-build
Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip install influxdb &&         pip install xmltodict &&         pip install pexpect &&         easy_install pysnmp &&         pip install lxml &&         pip install python-crontab &&         pip install git+https://github.com/Juniper/py-junos-eznc.git' returned a non-zero code: 1
lmurillo-mba:open-nti lmurillo$

**Comment by igorme** [comment] 2016-03-06 18:02
could you please share ready to use docker container?

**Comment by 3fr61n** [comment] 2016-03-06 19:53
Building the container with docker 1.7.0 works perfectly but after upgrade it to 1.10.1 and build it again, the problem you found arises.

**Comment by 3fr61n** [comment] 2016-03-06 20:36
I found some similar issues commented here about junos-eznc installation, http://forums.juniper.net/t5/Automation-Programmability/Python-for-Non-Programmers-Part-1/ba-p/216449

I modified the pyez installation in the Dockerfile, and so far it seems to work, please clone it and try again

**Comment by igorme** [comment] 2016-03-06 21:46
thanks a lot. everything is working

[SOLVED]

**Comment by 3fr61n** [comment] 2016-03-07 06:07
Fixed on commit 62d97cf8e78be801f05409506e67c512d62e1a40

**Closed by 3fr61n** 2016-03-07 06:07 UTC

**Comment by dgarros** [comment] 2016-03-07 06:21
For information, I just published open-nti to the docker cloud, so you don't need to "build it" anymore, you only need to start
https://hub.docker.com/r/juniper/open-nti/builds/
